spring:
  web:
    resources:
      static-locations:
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - /META-INF/resources/
        - classpath:/admin/

  #redis 配置
  redis:
    host: 127.0.0.1
    password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
    port: 6379

  # 消息队列配置
  artemis:
    broker-url: tcp://localhost:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)

jasypt:
  encryptor:
    password: 0ygWULnPXh8=

quan:
  app:
    feign:
      core:
        url: http://localhost:10010
      service:
        url: http://localhost:10011
  im:
    port: 10000
    websocket-path: /chat
#    reader-idle-time: 1800 #允许连接空闲的时间，单位：秒。超时后强制下线

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  # 打印sql
  level:
    cn.javaquan.im: debug

feign:
  client:
    config:
      default:
        loggerLevel: FULL # 日志级别
