spring:
  #redis 配置
  redis:
    host: redis
    password: ENC(LdfKiCk5MtqrEGQImE+I+yP4D6Dpi208)
    port: 6379

  datasource:
    url: jdbc:mysql://mysql:3306/quan-app?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(zy5LQYX+efbuK/ODrnWaOQ==)
    password: ENC(lUSPFgtmCpp1GghyEvRwQnfnciWxEHq3)

  # 邮箱配置
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: admin@quan.icu
    password: ENC(NjT3QSTB7K9Zh4XXCpUP634vLaCnnK4B)
    protocol: smtps

  # 消息队列配置
  artemis:
    broker-url: tcp://activemq:61616
    user: ENC(zNa29wR6KwuPzdYubZ46YQ==)
    password: ENC(zNa29wR6KwuPzdYubZ46YQ==)

  # MongoDB
  data:
    mongodb:
      uri: ENC(I83N1JWCu/hbjaV2grCT34Cx1LbbxxR32HBMTmogKbPI6OzKugNf2qorfsSYHk1H+XCXdmwV37gAgQNP1RUfWA==)

quan:
  app:
    feign:
      core:
        name: quan-app-core
        url: http://localhost:10020
      service:
        name: quan-app-service
        url: http://localhost:10020
      security:
        name: quan-security
        url: http://localhost:10020
  minio:
    host: http://minio:9000
    url: https://file.javaquan.cn
    access-key: ENC(WYSi3IxAUn8ZjtGW3zOEQuacKDsW4y8P)
    secret-key: ENC(LnvA210yPeTPAowASbCeWpWlYPoguvBm)
    default-bucket-name: public
  im:
    port: 10000
    websocket-path: /chat
    reader-idle-time: 1800 #允许连接空闲的时间，单位：秒。超时后强制下线
  tools:
    notify:
      printStackTrace: false
      exception-webhook: ENC(WYSi3YSKugi3IxAUn8ZjtGW3zOEQuI6OzKugNf2qoracKDu2qoacKDsW4y8P) # 使用 Webhook 地址，向钉钉群推送消息
      tag: quan-app # 机器人安全设置-自定义关键词


######  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1:10011/eureka/

alibaba:
  dingtalk:
    appkey: ENC(64Yw3NLthRazVp+egfu+IJEZ6n9EmkJOdg5huYMsLwE=)
    appSecret: ENC(K1OrngRTJLspT/j17plV9hGDxVpkjhhLcsZJW1QWs+bsU8rAweCQ10GQ3BN48luoQubrjaadWP83LSUbvpfjntZifB1oCr0PPJPkd+WIU50=)
