spring:
  #redis 配置
  redis:
    host: redis
    password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
    port: 6379

  datasource:
    dynamic:
      primary: quan-app # 设置默认的数据源或者数据源组,默认值: quan-app
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        quan-app:
          url: jdbc:mysql://mysql:3306/quan-app?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
          password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
        artalk: # artalk 评论系统
          url: jdbc:mysql://mysql:3306/artalk?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
          password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)

  # 邮箱配置
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: admin@quan.icu
    password: ENC(FSPtUGawJzJhY3BtyqXEI8Rx5OsDxhXL)
    protocol: smtps

  # 消息队列配置
  artemis:
    broker-url: tcp://activemq:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)

  # MongoDB
  data:
    mongodb:
      uri: mongodb://quan:123456@127.0.0.1:27017/quan-app

quan:
  app:
    feign:
      core:
        name: quan-app-core
        url: http://quan-app-application:10020
      service:
        name: quan-app-service
        url: http://quan-app-application:10020
      security:
        name: quan-security
        url: http://quan-app-application:10020

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

alibaba:
  dingtalk:
    appkey: ENC(R6rWECOqT1iSFLRlg/RI5XAk6jRjl9UsbXPhz5NEZLQ=)
    appSecret: ENC(+3ojnSVAyeQpsNFbY19E1f1NpltzLjyKZZmxu87mYitq5bupTxx90/uOGDJkebQOm2ew8uTL0iRbOEV6rkK2HYV2Cx+A04uLysYof0PvYd8=)
