spring:
  #redis 配置
  redis:
    host: 127.0.0.1
    password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
    port: 6379


  datasource:
    url: jdbc:mysql://localhost:3306/quan-app?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
    password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)

  # 邮箱配置
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: admin@quan.icu
    password: ENC(FSPtUGawJzJhY3BtyqXEI8Rx5OsDxhXL)
    protocol: smtps

  # 消息队列配置
  artemis:
    broker-url: tcp://localhost:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)

  # MongoDB
  data:
    mongodb:
      uri: mongodb://quan:123456@127.0.0.1:27017/quan-app

jasypt:
  encryptor:
    password: 0ygWULnPXh8=

quan:
  app:
    feign:
      core:
        name: quan-app-core
        url: http://localhost:10020
      service:
        name: quan-app-service
        url: http://localhost:10020
      security:
        name: quan-security
        url: http://localhost:10020
  minio:
    host: http://localhost:9000
    access-key: root
    secret-key: administrator
    default-bucket-name: public
  im:
    port: 10000
    websocket-path: /chat
    reader-idle-time: 1800 #允许连接空闲的时间，单位：秒。超时后强制下线
#    ssl:
#      enabled: true
#      # /// 仅测试使用的SSL证书。
#      key-cert-chain-file-path: ${用户目录}/quan/quan-app/quan-chat-bff/src/main/resources/test_cert.pem
#      key-file-path: ${用户目录}/quan/quan-app/quan-chat-bff/src/main/resources/test_private_pkcs8.pem
#
#server:
#  ssl:
#    enabled: true
#    key-store: classpath:test_cert.jks
#    key-store-password: javaquan
#    key-store-type: JKS

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com.quan: debug
feign:
  client:
    config:
      default:
        loggerLevel: FULL # 日志级别

alibaba:
  dingtalk:
    appkey: ENC(R6rWECOqT1iSFLRlg/RI5XAk6jRjl9UsbXPhz5NEZLQ=)
    appSecret: ENC(+3ojnSVAyeQpsNFbY19E1f1NpltzLjyKZZmxu87mYitq5bupTxx90/uOGDJkebQOm2ew8uTL0iRbOEV6rkK2HYV2Cx+A04uLysYof0PvYd8=)
