spring:
  #redis 配置
  redis:
    host: 127.0.0.1
    password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
    port: 6379

  datasource:
    dynamic:
      primary: quan-app # 设置默认的数据源或者数据源组,默认值: quan-app
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        quan-app:
          url: jdbc:mysql://localhost:3306/quan-app?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
          password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
        artalk: # artalk 评论系统
          url: jdbc:mysql://localhost:3306/artalk?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: ENC(N3N/kE3JUW6CffgwNeGZRQ==)
          password: ENC(N3N/kE3JUW6CffgwNeGZRQ==)

  # 消息队列配置
  artemis:
    broker-url: tcp://localhost:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)

  # MongoDB
  data:
    mongodb:
      uri: mongodb://quan:123456@127.0.0.1:27017/quan-app

jasypt:
  encryptor:
    password: 0ygWULnPXh8=

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    cn.javaquan: debug
feign:
  client:
    config:
      default:
        loggerLevel: FULL # 日志级别
