spring:
  #redis 配置
  redis:
    host: localhost
    password: 'root'
    port: 6379

  # 邮箱配置
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: admin@quan.icu
    password: ENC(FSPtUGawJzJhY3BtyqXEI8Rx5OsDxhXL)
    protocol: smtps

  # 消息队列配置
  artemis:
    broker-url: tcp://localhost:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)

jasypt:
  encryptor:
    password: 0ygWULnPXh8=

quan:
  app:
    feign:
      core:
        url: http://localhost:10010
      security:
        url: http://localhost:10020
  minio:
    host: http://localhost:9000
    access-key: root
    secret-key: administrator
    default-bucket-name: public

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    cn.javaquan: debug
feign:
  client:
    config:
      default:
        loggerLevel: FULL # 日志级别

alibaba:
  dingtalk:
    appkey: ENC(R6rWECOqT1iSFLRlg/RI5XAk6jRjl9UsbXPhz5NEZLQ=)
    appSecret: ENC(+3ojnSVAyeQpsNFbY19E1f1NpltzLjyKZZmxu87mYitq5bupTxx90/uOGDJkebQOm2ew8uTL0iRbOEV6rkK2HYV2Cx+A04uLysYof0PvYd8=)
