quan:
  app:
    feign:
      service:
        url: http://localhost:10011
      core:
        url: http://localhost:10010

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/