quan:
  app:
    feign:
      service:
        url: http://localhost:10011
      core:
        url: http://localhost:10010

#####  eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/