spring:
  #redis 配置
  redis:
    password: 'root'

  datasource:
    url: jdbc:mysql://mysqlservice:3306/quan-app?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
