spring:
  # 消息队列配置
  artemis:
    broker-url: tcp://activemq:61616
    user: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
    password: ENC(6RN5dJs4Ge4HA2uIwZJk1Q==)
  cloud:
    gateway:
      routes:
        - id: quan-app-aggregations
          uri: http://quan-app-aggregations:10020
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1

quan:
  app:
    security:
      url: http://quan-app-aggregations:10020
    auth-source:
      url: http://quan-app-aggregations:10020

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false