spring:
  # 消息队列配置
  artemis:
    broker-url: tcp://activemq:61616
    user: ENC(zNa29wR6KwuPzdYubZ46YQ==)
    password: ENC(zNa29wR6KwuPzdYubZ46YQ==)
  cloud:
    gateway:
      routes:
        - id: quan-app-aggregations
          uri: http://quan-app-aggregations:10020
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1

quan:
  app:
    security:
      url: http://quan-app-aggregations:10020
    auth-source:
      url: http://quan-app-aggregations:10020

#####  eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka:10011/eureka/
